spring:
  application:
    name: api-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskforge}
    username: ${DB_USERNAME:taskforge}
    password: ${DB_PASSWORD:taskforge}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
server:
  port: 8080
