spring:
  application:
    name: api-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskforge}
    username: ${DB_USERNAME:taskforge}
    password: ${DB_PASSWORD:taskforge}

  rabbitmq:
    username: ${RABBITMQ_USERNAME:taskforge}
    password: ${RABBITMQ_PASSWORD:taskforge}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
server:
  port: 8080
